version: '3'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    
  cass:
    build: cassandra
    volumes:
      - /Users/j0j00vi/Documents/SEDS/Week12/Hackathon2/cassandra/cass-data:/var/lib/cassandra 
    ports:
      - 9042:9042

  spark-node:
    build: spark-model
    volumes:
      - /Users/j0j00vi/Documents/SEDS/Week12/Hackathon2/data:/data
    ports:
      - 4040:4040

  front-end:
    build: front-end
    depends_on:
      - zookeeper
      - kafka
      - cass
      - spark-node
    ports:
      - 4000:4000

networks:
  default:
    external: true
    name: hack
